#!/usr/bin/env bash
# Regenerate the <script> tags that load JIZURA's engine from the submodule.
#
# JIZURA ships one classic script per module under src/ (they share the global `J`), loaded in
# filename order -- its own build.py just concatenates them. We load the same files directly,
# minus src/12_ui.js, which is JIZURA's editor UI and expects the editor's DOM.
#
# Run after moving the submodule to another JIZURA commit:
#   git -C web/vendor/JIZURA fetch --depth 1 origin main && git -C web/vendor/JIZURA checkout FETCH_HEAD
#   tools/update-jizura-scripts.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HTML="$ROOT/web/index.html"
SRC="$ROOT/web/vendor/JIZURA/src"

[[ -d "$SRC" ]] || { echo "missing $SRC -- run: git submodule update --init" >&2; exit 1; }

TAGS="$(cd "$SRC" && ls *.js | LC_ALL=C sort | grep -v '^12_ui\.js$' | sed 's|.*|<script src="vendor/JIZURA/src/&"></script>|')"

python3 - "$HTML" "$TAGS" <<'EOF'
import re, sys
path, tags = sys.argv[1], sys.argv[2]
html = open(path, encoding='utf-8').read()
block = '<!-- jizura:begin (generated by tools/update-jizura-scripts.sh) -->\n' + tags + '\n<!-- jizura:end -->'
new, n = re.subn(r'<!-- jizura:begin.*?<!-- jizura:end -->', lambda m: block, html, flags=re.S)
if n != 1: sys.exit('index.html: jizura:begin / jizura:end markers not found')
open(path, 'w', encoding='utf-8').write(new)
EOF

echo "index.html now loads $(printf '%s\n' "$TAGS" | wc -l | tr -d ' ') JIZURA scripts @ $(git -C "$ROOT/web/vendor/JIZURA" rev-parse --short HEAD)"
